name: Setup
description: Setup the environment

inputs:
  node-version:
    description: The version of node.js
    required: false
    default: '24'

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

    - name: Setup node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      run: pnpm install
      shell: bash
