name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

  publish:
    runs-on: ubuntu-latest
    needs: [release]
    if: jobs.release.outputs.release_created
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup

      - name: Publish to NPM
        run: echo publish
